---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studylife-developers-secrets
  namespace: studylife-developers
spec:
  encryptedData:
    StudyLifeDevelopers__SharedSecret: AgB03ggJfJFli5+g7h8L7Gq010/hwxKeJGR3B0Dg4ANeY0DS7DQBkiTzom2BGJmmOQoslM5cNUmaFPlLHSikCNfHVSnWNAdtZuIm3yTE8YHVF9y7fNwcoY62yf59yI9UGUj49PMK83YonCyD4E21qYNT6gtvpePiIcRKPpZksbS6BAYEBEeBd7xBLJgcUmfx9ITW+JB6Oj4s8VC+Ob3a3tcDY5d07c4SR2mF1pT2iCN+1M0bgWXe1wPvdaCdtRjQhsDPouQBUkVvsS8cuoxPMjwovBPQc3nvEtIWUKVb0mbaSOUr0t9i+NrV+319dkP4/hgOTdOpem+EoYdVD89joiOZH7NqYQwI4p+q0UI3cbSqgfDa3seyB0UI4QddlhVaZ1XVI+rYal7219HKYW5VYZbUa26wRnc7JiJNF/3weIM3RhBqRzXM9z6kwozFxOUm3Nvs+czum7EwgCDELR/t2HYlYqezOM8GiIXzU/8VBsR/XepkozaZcX27luwP3vYms1H9M4lo+4ZEtLxs6urw0eiLZMdQTDJyfoesq0Cb5y31B0oqyXdBFMMpy59DBkdUOS6p/RfLkL+Tav0si8iy/82Jf/FNt3Phh97VtLIJ2it8rQHusJNVHXG7G+0VvvdW6oea6nBJqD1r3R9qS38UHI581Lmkcopsup5YCmpjsDqUoVivkDLWy+fllKhA4KYwIhKt9k+0kmpuxgILqdNwveymxVThlYGc1Syp31aRd0yJAII7w8/wCHOdY1+dEw==
  template:
    metadata:
      name: studylife-developers-secrets
      namespace: studylife-developers
    type: Opaque
